### ISSUE TITLE
LDLite Breaks when Updating

### ISSUE THREAD

**Issue by jenmawe** [library-data-platform/ldlite#2] opened 2022-05-31 14:00 UTC
Reporting for a colleague at Five Colleges:

When upgrading LDLite, he was unable to do transformations. He fixed this with a downgrade to .31 and python 3.83.

"I'm running a windows system, with python 3.88.   LDlite is running in a virtual environment.  I did the standard pip -m .... to update.
didn't work so i created a new venv, also didn't work but that one was python 3.10.  Tried it in pipev too.  Unfortunately I've since reinstalled with  .31  in a python 3.83 venv, which is now working fine, i can't replicate it"

Error Message:
seen this ldplite error before?
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_42136/1165802898.py in <module>
----> 1 ld.query(table='p_users', path='/users', query='cql.allRecords=1 sortby id')
c:\Users\aneslin\Documents\python\ldplite\ldp\lib\site-packages\ldlite\__init__.py in query(self, table, path, query, json_depth, limit, transform)
    399             newattrs = {}
    400             if json_depth > 0:
--> 401                 jsontables, jsonattrs = _transform_json(self.db, self.dbtype, table, count, self._quiet, json_depth)
    402                 newtables += jsontables
    403                 newattrs = jsonattrs
c:\Users\aneslin\Documents\python\ldplite\ldp\lib\site-packages\ldlite\_jsonx.py in _transform_json(db, dbtype, table, total, quiet, max_depth)
    393         cur2 = db.cursor()
    394         while True:
--> 395             row = cur.fetchone()
    396             if row is None:
    397                 break
RuntimeError: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error:

**Comment by nassibnassar** [comment] 2022-05-31 14:57
I am not able to reproduce this error based on the information provided.  I suggest upgrading either Python or LDLite but not both at the same time, and then testing again.  Also please post the script that calls LDLite, with passwords etc. redacted.

**Comment by nassibnassar** [comment] 2022-09-20 17:46
@jenmawe  I think this is the bug that has been fixed in LDLite v0.0.33.

**Closed** 2022-11-01 19:57 UTC
